services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ..:/workspace:cached
      - node_modules:/workspace/node_modules:delegated
    command: sleep infinity
    ports:
      - "3000:3000"
      - "6006:6006"
    environment:
      - DATABASE_URL=postgresql://devuser:devsecret@devcontainer_db/devcontainer_db
      - NODE_ENV=development
    env_file:
      - ../.devcontainer.env
    depends_on:
      - devcontainer_db
    networks:
      - outside

  devcontainer_db:
    container_name: devcontainer_db
    image: postgres:17-alpine
    restart: always
    volumes:
      - ../.docker/devcontainer_postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=devsecret
      - POSTGRES_USER=devuser
      - POSTGRES_DB=devcontainer_db
    ports:
      - "5432:5432"
    networks:
      - outside

volumes:
  postgres-data:
  node_modules:
networks:
  outside:
